# generates an opening database from Playtak.com games database

name: create database release
  
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 2 * * 2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: download playtak games database
      run: |
        mkdir data
        wget -O data/games_anon.db https://www.playtak.com/games_anon.db
    - name: generate database
      run: |
        pip install pillow tqdm
        python TAKexplorer.py extract -i data/games_anon.db -o data/openings_s6_1200.db -p 12 -n 100000 -r 1200
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: data/openings_s6_1200.db
        asset_name: openings_s6_1200.db
        asset_content_type: text/plain
